version: "3"

services:
  backend:
    container_name: backend
    restart: always
    build: ./app
    volumes:
      - ./audio:/home/python/src/app/audio:ro
    environment:
      - AUDIO_PATH=/home/python/src/app/audio
      - MONGODB_URL=mongodb://root:pass@mongo:27018/duryssoile?retryWrites=true&w=majority&authSource=admin
    command: hypercorn -w 4 -b 0.0.0.0:80 main:app

  nginx:
    container_name: nginx-v2
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: duryssoile
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: nurzhan
#      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongo

volumes:
  mongo-data:
    driver: local

