version: "3"

services:
  backend:
    container_name: backend
    restart: always
    build: ./app
    volumes:
      - /home/vadmin/duryssoile/backend/audio:/home/python/src/app/audio:ro
    environment:
      - AUDIO_PATH=/home/python/src/app/audio
      - MONGODB_URL=mongodb://root:pass@mongo:27017?retryWrites=true&w=majority&authSource=admin
    command: hypercorn -w 4 -b 0.0.0.0:80 main:app

  nginx:
    container_name: nginx-v2
    restart: always
    image: nginx:mainline
    ports:
      - "80:80"
    volumes:
      - ./app.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - mongo
      - mongo-express

  mongo:
    image: mongo:4.4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: duryssoile
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express:latest
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: nurzhan
#      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongo

volumes:
  mongo-data:
    driver: local

